env: dev

http:
  host: localhost
  port: 8877

grpc:
  host: localhost
  port: 8855

logger:
  level: INFO
  file: logs/logger.json

database:
  host: localhost
  user: user
  password: D3cdF3z7Du90n1Sq
  name: calendar
  