env: dev

http:
  host: localhost
  port: 8080

grpc:
  host: localhost
  port: 8081

logger:
  level: INFO
  file: logs/logger.json

database:
  host: localhost
  port: 3306
  user: user
  password: D3cdF3z7Du90n1Sq
  name: calendar
